# Copyright Contributors to the L3AF Project.
# SPDX-License-Identifier: Apache-2.0
#
# For documentation on the format of this file, see
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  - package-ecosystem: "github-actions"
    # Workflow files are stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
