# Copyright Contributors to the L3AF Project.
# SPDX-License-Identifier: Apache-2.0
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI E2E build
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Update and firewall stop
        run: |
          sudo apt update
          sudo systemctl stop ufw
          sudo apt install -y iproute2
          sudo apt install git curl hey
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      
      - name: Prep
        run: |
          sudo cp -r /home/runner/work/l3afd/l3afd /root
          sudo git clone https://github.com/l3af-project/l3af-arch.git /root/l3af-arch
          sudo bash /root/l3af-arch/dev_environment/e2e_test/prep_env.sh
          sudo bash /root/l3af-arch/dev_environment/setup_linux_dev_env.sh --ci-build
          hm=$(hostname)
          sudo find /root/l3af-arch/dev_environment/e2e_test -type f -name "*.json" -exec sed -i "s/l3af-test-host/$hm/g" {} +
          
      - name: Run Tests
        run: |
         sudo bash /root/l3af-arch/dev_environment/e2e_test/test_suite.sh
